export const samplePhrases = [
  {
    id: '1',
    english: 'Hello, how are you?',
    russian: 'Привет, как дела?',
    pronunciation: 'Privet, kak dela?',
    meaning: 'Greeting and asking how someone is doing',
    example: 'A: Привет, как дела? B: Хорошо, спасибо! (Hello, how are you? Good, thanks!)',
    category: 'greetings',
    difficulty: 1,
    audioPath: '',
  },
  {
    id: '2',
    english: 'My name is...',
    russian: 'Меня зовут...',
    pronunciation: 'Menya zovut...',
    meaning: 'Introducing yourself by name',
    example: 'Меня зовут Иван. А как вас зовут? (My name is Ivan. And what is your name?)',
    category: 'introduction',
    difficulty: 1,
    audioPath: '',
  },
  {
    id: '3',
    english: 'I don\'t understand',
    russian: 'Я не понимаю',
    pronunciation: 'Ya ne ponimayu',
    meaning: 'Expressing that you don\'t understand something',
    example: 'Извините, я не понимаю. Вы можете говорить медленнее? (Sorry, I don\'t understand. Can you speak slower?)',
    category: 'communication',
    difficulty: 1,
    audioPath: '',
  },
  {
    id: '4',
    english: 'Where is the restroom?',
    russian: 'Где туалет?',
    pronunciation: 'Gde tualet?',
    meaning: 'Asking for the location of a restroom',
    example: 'Извините, где туалет? (Excuse me, where is the restroom?)',
    category: 'navigation',
    difficulty: 1,
    audioPath: '',
  },
  {
    id: '5',
    english: 'How much does it cost?',
    russian: 'Сколько это стоит?',
    pronunciation: 'Skol\'ko eto stoit?',
    meaning: 'Asking about the price of something',
    example: 'Сколько стоит эта книга? (How much does this book cost?)',
    category: 'shopping',
    difficulty: 1,
    audioPath: '',
  },
  {
    id: '6',
    english: 'I would like...',
    russian: 'Я хотел бы...',
    pronunciation: 'Ya khotel by...',
    meaning: 'Expressing a desire or wish',
    example: 'Я хотел бы чашку кофе, пожалуйста. (I would like a cup of coffee, please.)',
    category: 'restaurant',
    difficulty: 2,
    audioPath: '',
  },
  {
    id: '7',
    english: 'Do you speak English?',
    russian: 'Вы говорите по-английски?',
    pronunciation: 'Vy govorite po-angliyski?',
    meaning: 'Asking if someone speaks English',
    example: 'Извините, вы говорите по-английски? (Excuse me, do you speak English?)',
    category: 'communication',
    difficulty: 1,
    audioPath: '',
  },
  {
    id: '8',
    english: 'Thank you very much',
    russian: 'Большое спасибо',
    pronunciation: 'Bolshoye spasibo',
    meaning: 'Expressing gratitude with emphasis',
    example: 'Большое спасибо за вашу помощь! (Thank you very much for your help!)',
    category: 'greetings',
    difficulty: 1,
    audioPath: '',
  },
  {
    id: '9',
    english: 'I need help',
    russian: 'Мне нужна помощь',
    pronunciation: 'Mne nuzhna pomoshch',
    meaning: 'Requesting assistance',
    example: 'Извините, мне нужна помощь, я потерялся. (Excuse me, I need help, I am lost.)',
    category: 'emergency',
    difficulty: 2,
    audioPath: '',
  },
  {
    id: '10',
    english: 'I\'m sorry',
    russian: 'Извините',
    pronunciation: 'Izvinite',
    meaning: 'Apologizing for something',
    example: 'Извините за опоздание. (I\'m sorry for being late.)',
    category: 'communication',
    difficulty: 1,
    audioPath: '',
  },
];

export default samplePhrases;
